### ISSUE TITLE
Can we have charts for more than one month?

### ISSUE THREAD

**Issue by MatthieuHernandez** [Ameobea/osutrack-api#3]
It would be nice to see the evolution of the pp and rank since the creation of the Osu! account and not only the last month.

**Comment by Ameobea** [comment]
Hi,

This repository only contains the osu!track API, not the official osu! API or osu! website code.  osu!track starts tracking stats + hiscores from the first time a user's page is visited and that data is persisted forever.  Unfortunately you're right in that the official osu! API doesn't give historical data from long periods of time ago, that's why I created osu!track in the first place :)
