### ISSUE TITLE
osutrack website displaying 0% accuracy 

### ISSUE THREAD

**Issue by onlyatroller** [Ameobea/osutrack-api#6]
On the accuracy graph for [my osutrack profile](https://ameobea.me/osutrack/user/Troller) it randomly shows a dip to 0% accuracy and then goes back up to what it was before ruining the readability and scale of the graph. My account has never gone inactive and it does not show 0% on the osu website

![image](https://github.com/Ameobea/osutrack-api/assets/77567331/22e1e18f-9b74-44e3-8ff7-ef00c519d165)

**Comment by Ameobea** [comment]
Hi!  Yeah I see that, and I've seen issues like that on other users in the past.

As far as I can tell, it's just caused by blips on the osu! API side, but it could very well be some really weird edge in my code or something.

Anyway, I've deleted the bad updates for your user from the database and your chart looks nice now.  Ty for letting me know!
